/**
 * server.js — Binna API server
 *
 * Architecture:
 * 1. sbc-rules.js runs first — deterministic, no AI, always accurate
 * 2. Verified facts are injected into the Claude prompt
 * 3. Claude only writes the human-readable explanation — it invents NO facts
 */

const express = require('express');
const path    = require('path');
const Anthropic = require('@anthropic-ai/sdk');
const { runSBCChecks } = require('./sbc-rules');

const app    = express();
const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.get('/', (_req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));

function buildDeterministicReport(verifiedFacts) {
  return `## Feasibility Summary
This report is generated from deterministic Saudi Building Code and Baladiya rule checks. No AI-only assumptions were used.

## Compliance Findings
${verifiedFacts}

## Required Approvals
See the structured approvals list generated by the SBC rules engine.

## Cost Estimate
See the structured cost range generated from the project type, city, and BUA.

## Permit Timeline
See the structured permit timeline generated from city and project type.

## Key Recommendations
Resolve any listed violations before permit submission. Engage Civil Defense review early when required. Confirm all critical items with the local municipality.

Data source: Saudi Building Code 2021 + Baladiya guidelines (2024). Verify critical items with your local municipality before proceeding.`;
}

// ─── /api/analyze ─────────────────────────────────────────────────────────────
app.post('/api/analyze', async (req, res) => {
  const { city, type, plot, bua, floors, budget, zone, details } = req.body;

  // Validate minimum required fields
  if (!city || !type) {
    return res.status(400).json({ error: 'City and project type are required.' });
  }

  // Step 1: Run the SBC rules engine — pure logic, no AI
  const checks = runSBCChecks({ city, type, plot, bua, floors, zone, budget });

  // Step 2: Build a fact-locked prompt — Claude explains, never invents
  const verifiedFacts = `
VERIFIED SBC DATA (source: ${checks.dataSource}):

FAR Analysis:
${checks.farCalculated ? `- Calculated FAR: ${checks.farCalculated}` : '- FAR: Plot or BUA not provided'}
${checks.farLimit ? `- Zone FAR limit: ${checks.farLimit}` : ''}
${checks.flags.length > 0 ? `- VIOLATIONS: ${checks.flags.join(' | ')}` : '- FAR: No violations detected'}

Compliance Results:
- Passed checks: ${checks.passed.length > 0 ? checks.passed.join(' | ') : 'None'}
- Warnings: ${checks.warnings.length > 0 ? checks.warnings.join(' | ') : 'None'}
- Civil Defense required: ${checks.civilDefenseRequired ? 'YES' : 'Not mandatory for this scope'}
- Parking spaces required: ${checks.parkingRequired ? `~${checks.parkingRequired} spaces` : 'Not calculated'}

Cost Estimate:
${checks.costRange
  ? `- Range: ${checks.costRange.low.toLocaleString()} – ${checks.costRange.high.toLocaleString()} SAR
- Rate: ${checks.costRange.perSqmLow.toLocaleString()} – ${checks.costRange.perSqmHigh.toLocaleString()} SAR/m²
- Source: ${checks.costRange.source}
- Note: ${checks.costRange.note}`
  : '- BUA not provided — cannot estimate cost'}

Required Approvals (${checks.approvals.length} total):
${checks.approvals.map((a, i) => `${i + 1}. ${a}`).join('\n')}

Permit Timeline for ${city}:
- Estimated: ${checks.permitTimeline.minMonths}–${checks.permitTimeline.maxMonths} months (${checks.permitTimeline.minWeeks}–${checks.permitTimeline.maxWeeks} weeks)
- Note: ${checks.permitTimeline.note}

PROJECT INPUTS:
- City: ${city}
- Type: ${type}
- Plot: ${plot ? plot + ' m²' : 'Not provided'}
- BUA: ${bua ? bua + ' m²' : 'Not provided'}
- Floors: ${floors || 'Not provided'}
- Budget: ${budget || 'Not provided'}
- Zone: ${zone || 'Not specified'}
- Additional context: ${details || 'None'}
`.trim();

  const systemPrompt = `You are Binna, a Saudi construction feasibility analyst. 
Your job is to write a clear, professional feasibility report in English.

CRITICAL RULES:
1. You MUST use ONLY the verified data provided below. Do not add any facts, rules, or numbers that are not in the verified data section.
2. Do not invent zoning rules, cost estimates, timelines, or approval requirements.
3. If data is missing (e.g. plot area not provided), say so — do not estimate it.
4. Be direct and useful. Saudi developers and engineers are reading this.
5. Always end with: "Data source: Saudi Building Code 2021 + Baladiya guidelines (2024). Verify critical items with your local municipality before proceeding."

FORMAT your report with these exact sections:
## Feasibility Summary
## Compliance Findings  
## Required Approvals
## Cost Estimate
## Permit Timeline
## Key Recommendations`;

  const structured = {
    flags:           checks.flags,
    warnings:        checks.warnings,
    passed:          checks.passed,
    approvals:       checks.approvals,
    costRange:       checks.costRange,
    permitTimeline:  checks.permitTimeline,
    farCalculated:   checks.farCalculated,
    farLimit:        checks.farLimit,
    civilDefense:    checks.civilDefenseRequired,
    parking:         checks.parkingRequired,
    dataSource:      checks.dataSource,
  };

  if (!process.env.ANTHROPIC_API_KEY) {
    return res.json({
      report: buildDeterministicReport(verifiedFacts),
      structured,
    });
  }

  try {
    const response = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1500,
      system: systemPrompt,
      messages: [
        {
          role: 'user',
          content: `Write a feasibility report using ONLY this verified data:\n\n${verifiedFacts}`,
        },
      ],
    });

    const reportText = response.content
      .filter(b => b.type === 'text')
      .map(b => b.text)
      .join('');

    // Return both the structured data and the written report
    res.json({
      report: reportText,
      structured,
    });
  } catch (err) {
    console.error('Claude API error:', err);
    res.status(500).json({ error: 'Analysis failed. Please try again.' });
  }
});

// ─── /api/cost-estimate (live cost as user types) ─────────────────────────────
app.get('/api/cost-estimate', (req, res) => {
  const { city, type, bua } = req.query;
  const buaNum = parseFloat(bua) || 0;

  if (!type || buaNum <= 0) {
    return res.json({ costRange: null });
  }

  const checks = runSBCChecks({ city, type, bua, plot: 0, floors: 0, zone: '', budget: '' });
  res.json({ costRange: checks.costRange });
});

const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

const server = app.listen(PORT, HOST, () => {
  console.log(`Binna running on http://${HOST}:${PORT}`);
});

server.on('error', (err) => {
  console.error('Server startup error:', err);
  process.exit(1);
});
